runtime: nodejs16

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /.*
  static_files: build/index.html
  upload: build/index.html
- url: /(.*\.(json|ico|js|css))
  static_files: build/\1
  upload: build/.*\.(json|ico|js|css)
