name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # デプロイするブランチを指定

jobs:
  setup:
    name: Deploy
    runs-on: ubuntu-latest  # 実行環境を指定

    steps:
    - name: Checkout
      uses: actions/checkout@v3  # リポジトリのコードをチェックアウトする

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1  # Google Cloud SDKをセットアップする

    - name: Authenticate with gcloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # GCPのサービスアカウントキー

    - name: Configure gcloud
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}  # GCPのプロジェクトID

    - name: Create App Engine application if not exists
      run: |
        gcloud app describe || gcloud app create --region=asia-northeast2

    - name: Deploy to GCP
      run: |  # GCPにデプロイするコマンドを実行
        gcloud app deploy frontend/app.yaml --quiet
        gcloud app deploy backend/app.yaml --quiet
